backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
  site-domain: joeco.de

publish_mode: editorial_workflow

media_folder: "assets/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    sort: "date:desc"
    format: "yaml-frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Excerpt Seperator", name: "excerpt_seperator", widget: "hidden", default: "<!--more-->"}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "page"
    label: "Page"
    folder: "_pages"
    create: true
    slug: ".md"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["404", "about", "contact", "sitemap", "year-archive"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "//"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "layouts"
    label: "Layouts"
    folder: "_layouts"
    extension: "html"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}